# -*- coding: utf-8 -*-
"""Exercise 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vp-DA34jpRWTttPk47gXxJGYY6v1M3tF
"""

a = int(input("Input your favorite number = "))
print("My favourite number is = " + str(a))