# -*- coding: utf-8 -*-
"""Exercise 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NI9fx27ScOPeKw3r86fFzmE8OktsGcUh
"""

a="this is before the variable was changed"
print(a)
a="this is after the variable was changed"
print(a)