# -*- coding: utf-8 -*-
"""Exercise  3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_T3yYkyq1-egX2_ZZ5rdGunVD99i1RTA
"""

a="\tAhmed Raheem\n"
print(a)
print(a.strip())
print(a.lstrip())
print(a.rstrip())