# -*- coding: utf-8 -*-
"""Exercise 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WDnCEff3wg0T7gkNpbM1DVO8ctY6WbK0
"""

usb= "Total USB's bought is: "
amount="Total amount that is left: "
print(usb + str(int(50/6)))
print(amount + str(50%6))