# -*- coding: utf-8 -*-
"""Exercise 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OjFMfbjFcUvjSK0TrRNMsR8rgXvZp05C
"""

a='"Education is the most powerful tool we can use to change the world"'
print("Nelson Madela once said", a)